// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class usercanpostmanygamesrelationinit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usercanpostmanygamesrelationinit));
        
        string IMigrationMetadata.Id
        {
            get { return "202305140845278_user-can-post-many-games-relation-init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
