// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class gamescommentstableinit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gamescommentstableinit));
        
        string IMigrationMetadata.Id
        {
            get { return "202305021454076_games&comments-table-init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
